[profile.default]
solc = "0.8.24"
src = "contracts"
out = "artifacts"
libs = ["lib", "node_modules"]
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@fhevm/solidity/=node_modules/@fhevm/solidity/',
    'forge-std/=lib/forge-std/src/',
    'encrypted-types/=node_modules/encrypted-types/',
]
optimizer = true
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 100
seed = '0xdeadbeef'
max_test_rejects = 1000

